# Basic SSL enabled taky setup for oneliner install
version: "3.7"
services:
#This is responsible for routing messages
   taky-cot:
    image: skadakar/taky:safepoint
    container_name: taky-cot
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - mode=cot
    volumes:
      - /root/taky-data/:/data      
#This is responsible for routing data
   taky-data:
    image: skadakar/taky:safepoint
    container_name: taky-data
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - mode=data
    volumes:
      - /root/taky-data/:/data
